authors:
  Anzooooo:
    name: 王郅尊
    description: |
      中国科学院计算技术研究所工程师<br>“香山”开源高性能 RISC-V 处理器开发者<br>“一生一芯”大规模人才培养计划工程师、助教
    avatar: https://avatars.githubusercontent.com/u/126764519
    url: https://github.com/Anzooooo
